package com.visaulredactor.entity;

public enum ActionType {

    ADD_CHARACTER, REMOVE_CHARACTER, CHARACTER_SPEAK, NARRATOR_SPEAK, CHARACTER_SPRITE_CHANGE, BKG_CHANGE, MUSIC_CHANGE, SOUND_CHANGE, SCENE_CHANGE

}
